//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindForest.Models
{
    using System;
    
    public partial class NodeLookupInfo
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string CssClass { get; set; }
        public string Parent { get; set; }
        public string Lang { get; set; }
    }
}
