//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeText
    {
        public long Id { get; set; }
        public long NodeId { get; set; }
        public string Lang { get; set; }
        public int Position { get; set; }
        public string Title { get; set; }
        public string RichTitle { get; set; }
        public string Synopsis { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
    
        public virtual Node Node { get; set; }
    }
}
