//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionText
    {
        public long Id { get; set; }
        public long ConnectionId { get; set; }
        public string Lang { get; set; }
        public string StartText { get; set; }
        public string LineText { get; set; }
        public string EndText { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
    
        public virtual Connection Connection { get; set; }
    }
}
