//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindForest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public long NodeId { get; set; }
        public int RoleId { get; set; }
        public byte PermissionType { get; set; }
    
        public virtual Node Node { get; set; }
        public virtual Role Role { get; set; }
    }
}
